version: '3'
services:
  apaxy:
    image: apaxy
    build:
      context: .
      args:
        apaxyPath: ''
    ports:
      - '80:8080'
#    volumes:
#      - './share/:/usr/local/apache2/htdocs/share/'
    volumes:
      - '/home/derrend/:/usr/local/apache2/htdocs/home/'
      - '/media/derrend/derrend-media:/usr/local/apache2/htdocs/media/'
#      - '/home/derrend/GitHub/apaxy/httpd.conf:/usr/local/apache2/conf/httpd.conf'
#      - '/home/derrend/GitHub/apaxy/apaxy/.htpasswd:/usr/local/apache2/htdocs/.htpasswd'
    image: apaxy
